---
- import_tasks: Debian.yml
  when: ansible_os_family == 'Debian'
- import_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'
- name: run cgminer autogen
  become: false
  command: /bin/sh autogen.sh --enable-gekko {{ cgminer_additional_config }}
  args:
    chdir: /usr/local/src/cgminer
  environment:
    CFFLAGS: -02
- name: make cgminer
  become: false
  make:
    params:
      MAKEFLAGS: -j{{ compile_threads }}
      NUM_THREADS: "{{ compile_threads }}"
  args:
    chdir: /usr/local/src/cgminer
- name: install cgminer
  become: true
  make:
    target: install
  args:
    chdir: /usr/local/src/cgminer
- name: add user to udev group
  user:
    name: "{{ ansible_user }}"
    groups: plugdev
    append: yes
- name: copy udev rule for cgminer
  copy:
    src: /usr/local/src/cgminer/01-cgminer.rules
    dest: /etc/udev/rules.d/01-cgminer.rules
    owner: root
    group: root
    mode: 0644
    remote_src: yes