---
- name: install cgminer dependencies
  apt:
    state: present
    name: [
      'git',
      'libusb-1.0-0-dev',
      'libusb-1.0-0',
      'libudev-dev',
      'uthash-dev',
      'libjansson-dev',
      'libncurses5-dev',
      'libcurl4-gnutls-dev'
    ]
  register: result
  retries: 3
  delay: 10
  until: not result.failed