---
# tasks file for pi_install_cgminer
- name: check cgminer exists
  stat:
    path: /usr/local/bin/cgminer
  register: cgminer_check
- name: clone vthoang/cgminer
  git:
    repo: https://github.com/vthoang/cgminer.git
    dest: /usr/local/src/cgminer
    clone: yes
    update: yes
    recursive: yes
    version: "{{ cgminer_git_version }}"
  register: cgminer_repo
  retries: 3
  delay: 10
  until: not cgminer_repo.failed
- name: set user as owner of cgminer folder
  file:
    path: /usr/local/src/cgminer
    owner: "{{ ansible_user }}"
    recurse: true
- import_tasks: compile_cgminer.yml
  when: not cgminer_check.stat.exists or cgminer_repo.before != cgminer_repo.after
- include_tasks: configure_cgminer.yml
  with_items:
    - "{{ cgminer_config }}"