---
# handlers file for pi_install_cgminer
- name: reload systemd
  systemd:
    daemon_reload: yes
- name: restart cgminer
  systemd:
    name: cgminer.service
    state: "{{ 'restarted' if cgminer_autostart else 'stopped' }}"